reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
compiler:
  solc:
    version: 0.8.19
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env

networks:
  default: development
