reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    version: 0.8.15
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env

networks:
  default: development
